const JuicesList = [{
  id: 1,
  name: 'QUEMAGRASA',
  description: 'Piña, pepino, apio, espinaca, perejil, naranja, jengibre',
  color: '#579E3F',
  precio: 30,
},
{
  id: 2,
  name: 'REVITALIZANTE',
  description: 'Naranja, betabel, zanahoria, jengibre',
  color: '#C0303E',
  precio: 30,
},
{
  id: 3,
  name: 'QUITANTOJOS',
  description: 'Naranja, toronja, papaya, jengibre',
  color: '#D99230',
  precio: 30,
},
{
  id: 4,
  name: 'ENERGÉTICO',
  description: 'Piña, guayaba, naranja',
  color: '#DEDE41',
  precio: 30,
},
{
  id: 5,
  name: 'REJUVENECEDOR',
  description: 'Zanahoria, piña, naranja',
  color: '#DE9F31',
  precio: 30,
},
{
  id: 6,
  name: 'CÍTRICO',
  description: 'Kiwi, fresa, naranja',
  color: '#C0272A',
  precio: 30,
},
{
  id: 7,
  name: 'NEUTRALIZANTE',
  description: 'Papaya, fresa, naranja',
  color: '#D99230',
  precio: 30,
},
{
  id: 8,
  name: 'TROPICALÓN',
  description: 'Piña, plátano, mango',
  color: '#D5AE1C',
  precio: 30,
},
{
  id: 9,
  name: 'ANTIOXIDANTE',
  description: 'Zarzamora, blueberrys, frambuesa, fresa, naranja',
  color: '#82167E',
  precio: 30,
},
{
  id: 10,
  name: 'JUGO NARANJA',
  description: '100% jugo natural, exprimido al momento al momento',
  color: '#D4841E',
  precio: 25,
},
{
  id: 11,
  name: 'JUGO DE TORONJA',
  description: '100% jugo natural, hecho al momento',
  color: '#B68E82',
  precio: 25,
},
{
  id: 12,
  name: 'LIMONADA CON CHÍA',
  description: '100% jugo natural, exprimido al momento',
  color: '#B4C52D',
  precio: 20,
},
{
  id: 13,
  name: 'LIMONADA CON PEPINO',
  description: '100% jugo natural, exprimido al momento',
  color: '#3C9741',
  precio: 20,
},
{
  id: 13,
  name: 'LIMONADA CON FRESA',
  description: '100% jugo natural, exprimido al momento',
  color: '#3C9741',
  precio: 20,
},
{
  id: 14,
  name: 'NARANJADA',
  description: 'Hecho con jugo natural, exprimido al momento',
  color: '#D48448',
  precio: 20,
},
{
  id: 15,
  name: 'PERSONALIZADO',
  description: 'Escoge hasta 4 frutas/verduras: Fresa, papaya, melón, plátano, piña, naranja, limón, apio, jengibre, guayaba, espinaca, perejil,toronja,pepino',
  color: '#D5AE1C',
  precio: 30,
}];

export default JuicesList;
